### ISSUE TITLE
error with progressbar

### ISSUE THREAD

**Issue by Light--** [tsenst/CrowdFlow#6]
**error when using progressbar 2.5**

run opticalflow_evaluate.py, 
```
/usr/bin/python3.5 -u /home/xxx/CrowdFlow-master/opticalflow_evaluate.py /home/xxx/TUBCrowdFlow dual farneback plk
```
got error:
```
Traceback (most recent call last):
  File "/home/xxx/CrowdFlow-master/opticalflow_evaluate.py", line 92, in <module>
    main()
  File "/home/xxx/CrowdFlow-master/opticalflow_evaluate.py", line 74, in main
    bar.start(max_value=len(config_list) * len(parameter_list))
TypeError: start() got an unexpected keyword argument 'max_value'

Process finished with exit code 1
```
if edited the line 74#, replace max_value with maxval, still got error:
```

Traceback (most recent call last):
  File "/home/xxx/CrowdFlow-master/opticalflow_evaluate.py", line 92, in <module>
    main()
  File "/home/xxx/CrowdFlow-master/opticalflow_evaluate.py", line 74, in main
    bar.start(maxval=len(config_list) * len(parameter_list)) 
TypeError: start() got an unexpected keyword argument 'maxval'
```

**this can be fixed by using progressbar 3.46.1 (tested)**

**Comment by tsenst** [comment]
Please try to install `pip progressbar2` (the 2 is important) there is a differenze between _progressbar2_ and _progressbar_.

**Comment by Light--** [comment]
> Please try to install `pip progressbar2` (the 2 is important) there is a differenze between _progressbar2_ and _progressbar_.

thanks very much, i will try.
